"""Prompts for GPU to JAX conversion agent."""

from . import (
    identify_framework_prompt,
    organize_gpu_code_prompt,
    simplify_gpu_code_prompt,
    convert_to_jax_prompt,
    convert_simplified_to_jax_prompt,
    fix_conversion_prompt,
    fix_conversion_extended_prompt,
    summary_prompt,
    generate_summary_extended_prompt,
    orchestrator_prompt,
    analyze_plan_prompt,
    write_readme_prompt,
    validate_syntax_routing_prompt,
    validate_compilation_routing_prompt,
    validate_shapes_routing_prompt,
    generate_test_prompt,
    generate_test_extended_prompt,
    run_test_routing_prompt,
)

__all__ = [
    "identify_framework_prompt",
    "organize_gpu_code_prompt",
    "simplify_gpu_code_prompt",
    "convert_to_jax_prompt",
    "convert_simplified_to_jax_prompt",
    "fix_conversion_prompt",
    "fix_conversion_extended_prompt",
    "summary_prompt",
    "generate_summary_extended_prompt",
    "orchestrator_prompt",
    "analyze_plan_prompt",
    "identify_framework_prompt",
    "write_readme_prompt",
    "validate_syntax_routing_prompt",
    "validate_compilation_routing_prompt",
    "validate_shapes_routing_prompt",
    "generate_test_prompt",
    "generate_test_extended_prompt",
    "run_test_routing_prompt",
]
