"""
Step 3: Auto-detect model files and merge them into a single file.

This script scans the cloned repository to find all Python files that
define PyTorch nn.Module subclasses (the model code). It then merges
them into a single file in dependency order, so MaxCode can convert
the entire model with full context in one pass.

Non-model files (datasets, training scripts, utilities, etc.) are
automatically excluded. Relative imports between model files are
removed since all code is combined into one file.

Requires:
  - Step 1 completed (repo cloned)

Usage:
    python step3_merge.py
"""

import ast
import os
from config import REPO_DIR, MERGED_FILE


def is_model_file(file_path):
    """Detect if a Python file defines any nn.Module subclass."""
    try:
        with open(file_path, "r", encoding="utf-8", errors="replace") as f:
            code = f.read()
        tree = ast.parse(code)
    except SyntaxError:
        return False

    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            for base in node.bases:
                if isinstance(base, ast.Attribute) and base.attr == "Module":
                    return True
                if isinstance(base, ast.Name) and base.id == "Module":
                    return True
    return False


def find_model_files(repo_dir):
    """Walk the repo and return paths of files containing nn.Module classes."""
    model_files = []
    for root, _, files in os.walk(repo_dir):
        for f in sorted(files):
            if not f.endswith(".py"):
                continue
            full = os.path.join(root, f)
            if is_model_file(full):
                model_files.append(full)
    return model_files


def merge_files(file_paths, repo_dir, output_path):
    """Merge model files into a single file with imports de-duplicated."""
    import_lines = set()
    code_sections = []

    for full_path in file_paths:
        rel = os.path.relpath(full_path, repo_dir)
        with open(full_path, "r", encoding="utf-8") as f:
            content = f.read()

        section_lines = []
        in_docstring = False
        for line in content.split("\n"):
            stripped = line.strip()
            # Track triple-quoted strings (docstrings / multi-line comments)
            triple_count = stripped.count('"""') + stripped.count("'''")
            if triple_count % 2 == 1:
                in_docstring = not in_docstring
            # Inside a docstring, keep the line as-is
            if in_docstring or triple_count > 0:
                section_lines.append(line)
                continue
            # Skip relative imports (handled by merging)
            if stripped.startswith("from .") or stripped.startswith("from .."):
                continue
            # Collect standard imports (only at top-level indentation)
            if not line[:1].isspace() and (
                stripped.startswith("import ") or stripped.startswith("from ")
            ):
                import_lines.add(line)
            else:
                section_lines.append(line)

        code_sections.append(
            f"\n# {'=' * 70}\n# From {rel}\n# {'=' * 70}\n"
            + "\n".join(section_lines)
        )

    header = '"""\nMerged model file — auto-generated by step3_merge.py\n'
    header += f"Source: {repo_dir}\n"
    header += f"Files:  {len(file_paths)} model files detected\n"
    header += '"""\n\n'

    merged = header + "\n".join(sorted(import_lines)) + "\n" + "\n".join(code_sections)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(merged)

    return merged


def main():
    if not os.path.isdir(REPO_DIR):
        print("ERROR: Repository not found. Run step1_clone_repo.py first.")
        raise SystemExit(1)

    print("=" * 70)
    print("Step 3: Auto-Detect and Merge Model Files")
    print("=" * 70)
    print(f"  Scanning: {REPO_DIR}")
    print()

    # Scan all .py files
    all_py = []
    for root, _, files in os.walk(REPO_DIR):
        for f in sorted(files):
            if f.endswith(".py"):
                all_py.append(os.path.join(root, f))

    print(f"  Found {len(all_py)} Python files total")
    print()

    # Detect model files
    model_files = find_model_files(REPO_DIR)

    print("  Model files detected (contain nn.Module):")
    total_lines = 0
    for full_path in model_files:
        rel = os.path.relpath(full_path, REPO_DIR)
        lines = sum(1 for _ in open(full_path, encoding="utf-8"))
        total_lines += lines
        print(f"    {rel} ({lines} lines)")

    skipped = len(all_py) - len(model_files)
    print(f"\n  Skipped {skipped} non-model files (datasets, training, utils, etc.)")

    # Merge
    print(f"\n  Merging into: {MERGED_FILE}")
    merged = merge_files(model_files, REPO_DIR, MERGED_FILE)
    merged_lines = merged.count("\n") + 1
    print(f"  Merged file: {merged_lines} lines, {len(merged)} chars")

    print("\nStep 3 complete.")


if __name__ == "__main__":
    main()
