load("//learning/gemini/agents/skills/skill_creator/scripts:skill_defs.bzl", "validate_skill_test")

package(default_visibility = ["//experimental/llm_inference_on_tpu:__subpackages__"])

validate_skill_test(
    name = "validate_skill_test",
)
