"""Profiling subagent - performance profiling and analysis."""

import logging
from typing import AsyncGenerator


from google.adk.agents import SequentialAgent

from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions

from auto_agent.callbacks import (
  load_profiling_script_to_state,
  load_single_kernel_to_state,
)
from auto_agent.config import model_config, thinking_planner
from auto_agent.constants import MODEL_NAME
from auto_agent.custom_types import CustomLlmAgent
from auto_agent.subagents.profiling import offline_tools
from auto_agent.subagents.profiling.kernel_profile import KernelProfiler
from auto_agent.subagents.profiling.prompts import (
  analyze_profile_prompt,
  gen_profiling_script,
  read_file_prompt,
  read_profiling_script_prompt,
)
from auto_agent.tools.tools import filesystem_tool_r, filesystem_tool_rw, vertex_ai_rag_tool

# Read file agent for profiling
read_file_for_profiling_agent = CustomLlmAgent(
  name="ReadFileForProfilingAgent",
  model=MODEL_NAME,
  generate_content_config=model_config,
  planner=thinking_planner,
  instruction=read_file_prompt.PROMPT,
  description="Reads the kernel file mentioned by the user for profiling analysis.",
  tools=[filesystem_tool_r],
)

# Profiling script generation agent - writes profiling script to file
generate_profiling_script_agent = CustomLlmAgent(
  name="GenerateProfilingScriptAgent",
  model=MODEL_NAME,
  generate_content_config=model_config,
  planner=thinking_planner,
  instruction=gen_profiling_script.PROMPT,
  description="Generates a profiling script to identify performance bottlenecks in the kernel code and writes it to a file.",
  tools=[filesystem_tool_rw],
  before_agent_callback=load_single_kernel_to_state,
)

# Read profiling script agent - loads the generated profiling script file contents into state
read_profiling_script_agent = CustomLlmAgent(
  name="ReadProfilingScriptAgent",
  model=MODEL_NAME,
  generate_content_config=model_config,
  planner=thinking_planner,
  instruction=read_profiling_script_prompt.PROMPT,
  description="Loads the generated profiling script file contents from disk into memory for execution.",
  before_agent_callback=load_profiling_script_to_state,
  include_contents="none",
)

# Profiling execution agent
eval_profile_agent = KernelProfiler(
  name="ProfileEvalAgent",
  input_key="profiling_script",
  output_key="profiling_results",
)


class SummarizeProfileAgent(CustomLlmAgent):
  """Custom agent that generates a summary and makes a boolean decision on improvement."""

  async def _run_async_impl(
    self, ctx: InvocationContext
  ) -> AsyncGenerator[Event, None]:
    # 1. Run the normal LLM summary generation
    async for event in super()._run_async_impl(ctx):
      yield event

    # 2. Retrieve the summary generated by the parent call
    summary = ctx.session.state.get("profiling_summary", "")

    # 3. Parse the decision from the summary
    needs_improvement = True  # Default fallback
    import re
    match = re.search(
      r"NEEDS[-_\s]?IMPROVEMENT\s*[:=]\s*(TRUE|FALSE|YES|NO)",
      summary,
      re.IGNORECASE,
    )
    if match:
      decision = match.group(1).upper()
      if decision in ["FALSE", "NO"]:
        needs_improvement = False
      elif decision in ["TRUE", "YES"]:
        needs_improvement = True
      logging.info(f"[{self.name}] Parsed decision '{decision}' from summary.")
    else:
      logging.warning(
        f"[{self.name}] Could not parse decision from summary. Defaulting to True."
      )

    # 4. Direct inject the boolean into state
    logging.info(
      f"[{self.name}] Agent decision: needs_improvement = {needs_improvement}"
    )
    yield Event(
      author=self.name,
      actions=EventActions(
        state_delta={"needs_improvement": needs_improvement}
      ),
    )


# Profiling summary agent
summarize_profile_agent = SummarizeProfileAgent(
  name="SummarizeProfileAgent",
  model=MODEL_NAME,
  generate_content_config=model_config,
  planner=thinking_planner,
  instruction=analyze_profile_prompt.PROMPT,
  description=(
    "Summarizes the profiling results of the kernel and performs deep"
    " analysis using offline XProf tools."
  ),
  output_key="profiling_summary",
  include_contents="none",
  tools=[
    offline_tools.load_xplane_and_query,
    offline_tools.get_hlo_dump,
    offline_tools.create_chart_from_xplane,
    offline_tools.get_overview_page_metrics,
    vertex_ai_rag_tool,
  ],
)

# Main profiling orchestrator agent
profile_agent = SequentialAgent(
  name="ProfileAgentOrchestrator",
  sub_agents=[
    read_file_for_profiling_agent,
    generate_profiling_script_agent,
    read_profiling_script_agent,
    eval_profile_agent,
    summarize_profile_agent,
  ],
  description="Profiles the Pallas kernel to identify performance bottlenecks.",
)

__all__ = [
  "profile_agent",
  "read_file_for_profiling_agent",
  "generate_profiling_script_agent",
  "read_profiling_script_agent",
  "eval_profile_agent",
  "summarize_profile_agent",
]
