TPU_PALLAS_OPTIMIZATION_STRATEGIES = [
  "Reduce data movement",
  "Overlap data movement and compute",
  "Cache reused data in local memory instead of reloading from main memory",
  "Loop tiling",
  "Loop reordering and restructuring",
  "Loop unrolling",
  "Fuse operations",
  "Use lower precision",
  "Double buffering",
  "Software pipelining",
  "Hoist redundant operations out of loops",
  "Eliminate redundant computation",
  "Simplify or remove unnecessary code",
  "Try new parameter values",
  "Rewrite the algorithm to reduce total work",
  "Place reduction axis last in grid to enable in-place SRAM accumulation without HBM round-trips",
  "Align block dimensions to 8x128 tile boundaries to avoid wasted padding and register spills",
  "Use scratch_shapes=[pltpu.VMEM(...)] for persistent high-precision accumulators during reduction loops",
  "Maximize block sizes up to ~16 MB VMEM capacity to increase arithmetic intensity per pipeline step",
  "Use scalar prefetch via PrefetchScalarGridSpec to load indices/metadata into SMEM without stalling vector core",
  "Upcast bf16/int8 to float32 before elementwise ops, downcast only on final output write",
  "Fuse transpose into lax.dot_general contraction dimensions instead of materializing transposed operands",
  "Arrange grid iteration order so consecutive invocations reuse already-resident input slices",
  "Increase pipeline buffer count beyond double buffering to hide memory latency for bandwidth-bound kernels",
  "Generate random numbers inside kernel via hardware PRNG with key in SMEM instead of passing precomputed arrays",
  "Avoid singleton dimensions in last two array axes to prevent full-tile waste per element",
  "Reduce along second-to-last dimension rather than last dimension when possible",
  "Prefer add/multiply over exp/tanh/division; restructure math to minimize expensive elementwise ops",
  "Tune block sizes jointly — systematically vary BM, BN, BK together under the VMEM budget constraint (16 MiB including double-buffering)",
  "Compute arithmetic intensity accounting for tiling amplification to predict compute-bound vs memory-bound regime",
  "Minimize control flow inside kernels; consolidate into single basic blocks to avoid unrolling overhead",
  "Pass all data as explicit kernel inputs with BlockSpec instead of closing over constants",
  "Use pltpu.VMEM scoped scratch buffers for temporary storage within kernel lifetime",
  "Balance block size against pipeline depth to amortize startup/drain bubble cost over enough iterations",
  "Explicitly initialize accumulator buffers to zero on first reduction iteration since SRAM starts undefined",
]
